server:
  port: 7777

spring:
  application:
    name: Ammunition Helper
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/ammo_db
    username: admin
    password: changeme
